export const ADD_SECTION = "ADD_SECTION";
export const DEL_SECTION = "DEL_SECTION";
export const ADD_MACHINE = "ADD_MACHINE";
export const DEL_MACHINE = "DEL_MACHINE";
export const START_PROCESS = "START_PROCESS";
export const COMPLETE_PROCESS = "COMPLETE_PROCESS";
export const ADD_COMPONENT = "ADD_COMPONENT";
export const HANDLE_PLANNING = "HANDLE_PLANNING";
