export const ADD_PURCHASE_ORDER = "ADD_PURCHASE_ORDER";
export const DEL_PURCHASE_ORDER = "DEL_PURCHASE_ORDER";
export const REV_PURCHASE_ORDER = "REV_PURCHASE_ORDER";
export const ADD_REQUEST = "ADD_REQUEST";
export const REV_REQUEST = "REV_REQUEST";
export const COM_REQUEST = "COM_REQUEST";
