export const ADD_MATERIAL = "ADD_MATERIAL";
export const ADJ_MATERIAL = "ADJ_MATERIAL";
export const ADJ_FINISH_GOOD = "ADJ_FINISH_GOOD";
export const ADD_MAT_REQUEST = "ADD_MAT_REQUEST";
export const REV_MAT_REQUEST = "REV_MAT_REQUEST";
export const COM_MAT_REQUEST = "COM_MAT_REQUEST";
export const ADD_TRANSACTION = "ADD_TRANSACTION";
export const COM_TRANSACTION = "COM_TRANSACTION";
